INSERT INTO libro (id, anno_pubblicazione, titolo, url_image) VALUES (1, 2024, 'Dare la vita', 'https://m.media-amazon.com/images/I/61GB4vusnaL._SL160_.jpg');
INSERT INTO libro (id, anno_pubblicazione, titolo, url_image) VALUES (2, 2014, 'I viaggi di Gulliver', 'https://m.media-amazon.com/images/I/41Opup60jrL._SL160_.jpg');
INSERT INTO libro (id, anno_pubblicazione, titolo, url_image) VALUES (3, 2007, 'L amante di Lady Chatterley', 'https://m.media-amazon.com/images/I/41BZbDYLV2L._SL160_.jpg');
INSERT INTO libro (id, anno_pubblicazione, titolo, url_image) VALUES (4, 2016, 'Quel che resta del giorno', 'https://m.media-amazon.com/images/I/41eeO--NzIL._SL160_.jpg');
INSERT INTO libro (id, anno_pubblicazione, titolo, url_image) VALUES (5, 2019, 'Il buio oltre la siepe', 'https://m.media-amazon.com/images/I/51AHgdeEBAL._SL160_.jpg');

INSERT INTO autore (id, cognome, data_morte, data_nascita, fotografia, nazionalità, nome) VALUES (1, 'Murgia', NULL, '1972-06-03', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Festival_della_mente_2018.png/500px-Festival_della_mente_2018.png', 'italiana', 'Michela');
INSERT INTO autore (id, cognome, data_morte, data_nascita, fotografia, nazionalità, nome) VALUES (2, 'Swift', '1745-10-19', '1667-11-30', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Jonathan_Swift_by_Charles_Jervas_detail.jpg/330px-Jonathan_Swift_by_Charles_Jervas_detail.jpg', 'irlandese', 'Jonathan');
INSERT INTO autore (id, cognome, data_morte, data_nascita, fotografia, nazionalità, nome) VALUES (3, 'Herbert', '1930-03-02', '1885-09-11', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/D_H_Lawrence_passport_photograph.jpg/500px-D_H_Lawrence_passport_photograph.jpg', 'britannico', 'David');
INSERT INTO autore (id, cognome, data_morte, data_nascita, fotografia, nazionalità, nome) VALUES (4, 'Ishiguro', NULL, '1954-11-08', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Kazuo_Ishiguro_in_2017_01.jpg/500px-Kazuo_Ishiguro_in_2017_01.jpg', 'giapponese', 'Kazuo');
INSERT INTO autore (id, cognome, data_morte, data_nascita, fotografia, nazionalità, nome) VALUES (5, 'Lee', '2016-02-19', '1926-04-28', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/HarperLee_2007Nov05.jpg', 'americana', 'Harper');